<?php
// database/seeders/UserSeeder.php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run()
    {
        // Create admin user
        User::create([
            'name' => 'System Administrator',
            'email' => 'admin@admin.com',
            'password' => Hash::make('123456'),
            'role' => 'admin',
            'status' => 'active',
            'approved_at' => now(),
            'approved_by' => 'system',
        ]);

        // Create staff user
        User::create([
            'name' => 'Staff Member',
            'email' => 'staff@aurorawater.com',
            'password' => Hash::make('123456'),
            'role' => 'staff',
            'status' => 'active',
            'position' => 'Billing Officer',
            'approved_at' => now(),
            'approved_by' => 'admin',
        ]);

        // Create client user
        User::create([
            'name' => 'John Client',
            'email' => 'client@aurorawater.com',
            'wws_id' => 'WWS001',
            'password' => Hash::make('123456'),
            'role' => 'client',
            'status' => 'active',
            'service' => 'residential',
            'address' => '123 Main St, Aurora',
            'contact_number' => '09123456789',
            'approved_at' => now(),
            'approved_by' => 'staff',
        ]);

        // Create another client for testing
        User::create([
            'name' => 'Maria Santos',
            'email' => 'maria@aurorawater.com',
            'wws_id' => 'WWS002',
            'password' => Hash::make('123456'),
            'role' => 'client',
            'status' => 'active',
            'service' => 'commercial',
            'address' => '456 Business Ave, Aurora',
            'contact_number' => '09198765432',
            'approved_at' => now(),
            'approved_by' => 'staff',
        ]);

        // Create pending client for testing approvals
        User::create([
            'name' => 'Pending User',
            'email' => 'pending@aurorawater.com',
            'wws_id' => 'WWS003',
            'password' => Hash::make('123456'),
            'role' => 'client',
            'status' => 'pending',
            'service' => 'residential',
            'address' => '789 Pending St, Aurora',
            'contact_number' => '09111222333',
        ]);

        // Additional Active Staff Users (20+)
        $activeStaffUsers = [
            [
                'name' => 'Sarah Johnson',
                'email' => 'sarah.johnson@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'active',
                'position' => 'Customer Service Representative',
                'approved_at' => now(),
                'approved_by' => 'admin',
            ],
            [
                'name' => 'Michael Chen',
                'email' => 'michael.chen@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'active',
                'position' => 'Billing Supervisor',
                'approved_at' => now(),
                'approved_by' => 'admin',
            ],
            [
                'name' => 'Emily Rodriguez',
                'email' => 'emily.rodriguez@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'active',
                'position' => 'Collections Officer',
                'approved_at' => now(),
                'approved_by' => 'admin',
            ],
            [
                'name' => 'David Thompson',
                'email' => 'david.thompson@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'active',
                'position' => 'Technical Support',
                'approved_at' => now(),
                'approved_by' => 'admin',
            ],
            [
                'name' => 'Lisa Wang',
                'email' => 'lisa.wang@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'active',
                'position' => 'Account Manager',
                'approved_at' => now(),
                'approved_by' => 'admin',
            ],
            [
                'name' => 'Robert Garcia',
                'email' => 'robert.garcia@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'active',
                'position' => 'Field Operations Coordinator',
                'approved_at' => now(),
                'approved_by' => 'admin',
            ],
            [
                'name' => 'Jennifer Martinez',
                'email' => 'jennifer.martinez@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'active',
                'position' => 'Compliance Officer',
                'approved_at' => now(),
                'approved_by' => 'admin',
            ],
            [
                'name' => 'Kevin Brown',
                'email' => 'kevin.brown@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'active',
                'position' => 'IT Support Specialist',
                'approved_at' => now(),
                'approved_by' => 'admin',
            ],
            [
                'name' => 'Amanda Wilson',
                'email' => 'amanda.wilson@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'active',
                'position' => 'Senior Billing Officer',
                'approved_at' => now(),
                'approved_by' => 'admin',
            ],
            [
                'name' => 'James Lee',
                'email' => 'james.lee@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'active',
                'position' => 'Customer Relations Manager',
                'approved_at' => now(),
                'approved_by' => 'admin',
            ],
            [
                'name' => 'Michelle Taylor',
                'email' => 'michelle.taylor@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'active',
                'position' => 'Finance Analyst',
                'approved_at' => now(),
                'approved_by' => 'admin',
            ],
            [
                'name' => 'Daniel Kim',
                'email' => 'daniel.kim@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'active',
                'position' => 'Operations Supervisor',
                'approved_at' => now(),
                'approved_by' => 'admin',
            ],
            [
                'name' => 'Nicole Anderson',
                'email' => 'nicole.anderson@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'active',
                'position' => 'Quality Assurance Specialist',
                'approved_at' => now(),
                'approved_by' => 'admin',
            ],
            [
                'name' => 'Christopher Davis',
                'email' => 'christopher.davis@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'active',
                'position' => 'Training Coordinator',
                'approved_at' => now(),
                'approved_by' => 'admin',
            ],
            [
                'name' => 'Stephanie White',
                'email' => 'stephanie.white@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'active',
                'position' => 'HR Coordinator',
                'approved_at' => now(),
                'approved_by' => 'admin',
            ],
        ];

        // Additional Pending Staff Users (20+)
        $pendingStaffUsers = [
            [
                'name' => 'Brian Miller',
                'email' => 'brian.miller.pending@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'pending',
                'position' => 'Facilities Manager',
            ],
            [
                'name' => 'Rachel Moore',
                'email' => 'rachel.moore.pending@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'pending',
                'position' => 'Public Relations Officer',
            ],
            [
                'name' => 'Jason Clark',
                'email' => 'jason.clark.pending@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'pending',
                'position' => 'Data Analyst',
            ],
            [
                'name' => 'Melissa Harris',
                'email' => 'melissa.harris.pending@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'pending',
                'position' => 'Administrative Assistant',
            ],
            [
                'name' => 'Steven Lewis',
                'email' => 'steven.lewis.pending@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'pending',
                'position' => 'Technical Writer',
            ],
            [
                'name' => 'Jessica Walker',
                'email' => 'jessica.walker.pending@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'pending',
                'position' => 'Compliance Auditor',
            ],
            [
                'name' => 'Thomas Hall',
                'email' => 'thomas.hall.pending@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'pending',
                'position' => 'Systems Administrator',
            ],
            [
                'name' => 'Ashley Young',
                'email' => 'ashley.young.pending@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'pending',
                'position' => 'Customer Success Manager',
            ],
            [
                'name' => 'Mark Robinson',
                'email' => 'mark.robinson.pending@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'pending',
                'position' => 'Network Engineer',
            ],
            [
                'name' => 'Laura Scott',
                'email' => 'laura.scott.pending@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'pending',
                'position' => 'Database Administrator',
            ],
            [
                'name' => 'Eric King',
                'email' => 'eric.king.pending@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'pending',
                'position' => 'Security Specialist',
            ],
            [
                'name' => 'Megan Green',
                'email' => 'megan.green.pending@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'pending',
                'position' => 'Project Coordinator',
            ],
            [
                'name' => 'Andrew Adams',
                'email' => 'andrew.adams.pending@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'pending',
                'position' => 'Business Analyst',
            ],
            [
                'name' => 'Rebecca Baker',
                'email' => 'rebecca.baker.pending@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'pending',
                'position' => 'Marketing Specialist',
            ],
            [
                'name' => 'Joshua Carter',
                'email' => 'joshua.carter.pending@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'pending',
                'position' => 'Software Developer',
            ],
            [
                'name' => 'Olivia Mitchell',
                'email' => 'olivia.mitchell.pending@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'pending',
                'position' => 'UX Designer',
            ],
            [
                'name' => 'Brandon Perez',
                'email' => 'brandon.perez.pending@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'pending',
                'position' => 'DevOps Engineer',
            ],
            [
                'name' => 'Hannah Roberts',
                'email' => 'hannah.roberts.pending@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'pending',
                'position' => 'Content Writer',
            ],
            [
                'name' => 'Justin Turner',
                'email' => 'justin.turner.pending@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'pending',
                'position' => 'Social Media Manager',
            ],
            [
                'name' => 'Victoria Phillips',
                'email' => 'victoria.phillips.pending@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'pending',
                'position' => 'Recruitment Specialist',
            ],
            [
                'name' => 'Samuel Campbell',
                'email' => 'samuel.campbell.pending@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'pending',
                'position' => 'Legal Assistant',
            ],
            [
                'name' => 'Brittany Parker',
                'email' => 'brittany.parker.pending@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'pending',
                'position' => 'Event Coordinator',
            ],
            [
                'name' => 'Patrick Evans',
                'email' => 'patrick.evans.pending@aurorawater.com',
                'password' => Hash::make('123456'),
                'role' => 'staff',
                'status' => 'pending',
                'position' => 'Inventory Manager',
            ],
        ];

        // Additional Active Client Users (20+)
        $activeClientUsers = [
            [
                'name' => 'Carlos Reyes',
                'email' => 'carlos.reyes@aurorawater.com',
                'wws_id' => 'WWS004',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'active',
                'service' => 'residential',
                'address' => '101 Oak Street, Aurora',
                'contact_number' => '09122334455',
                'approved_at' => now(),
                'approved_by' => 'staff',
            ],
            [
                'name' => 'Sophia Gonzalez',
                'email' => 'sophia.gonzalez@aurorawater.com',
                'wws_id' => 'WWS005',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'active',
                'service' => 'commercial',
                'address' => '202 Pine Avenue, Aurora',
                'contact_number' => '09133445566',
                'approved_at' => now(),
                'approved_by' => 'staff',
            ],
            [
                'name' => 'Miguel Torres',
                'email' => 'miguel.torres@aurorawater.com',
                'wws_id' => 'WWS006',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'active',
                'service' => 'institutional',
                'address' => '303 Maple Road, Aurora',
                'contact_number' => '09144556677',
                'approved_at' => now(),
                'approved_by' => 'staff',
            ],
            [
                'name' => 'Isabella Cruz',
                'email' => 'isabella.cruz@aurorawater.com',
                'wws_id' => 'WWS007',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'active',
                'service' => 'residential',
                'address' => '404 Cedar Lane, Aurora',
                'contact_number' => '09155667788',
                'approved_at' => now(),
                'approved_by' => 'staff',
            ],
            [
                'name' => 'Eduardo Ramos',
                'email' => 'eduardo.ramos@aurorawater.com',
                'wws_id' => 'WWS008',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'active',
                'service' => 'commercial',
                'address' => '505 Elm Street, Aurora',
                'contact_number' => '09166778899',
                'approved_at' => now(),
                'approved_by' => 'staff',
            ],
            [
                'name' => 'Valentina Morales',
                'email' => 'valentina.morales@aurorawater.com',
                'wws_id' => 'WWS009',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'active',
                'service' => 'residential',
                'address' => '606 Birch Avenue, Aurora',
                'contact_number' => '09177889900',
                'approved_at' => now(),
                'approved_by' => 'staff',
            ],
            [
                'name' => 'Ricardo Chavez',
                'email' => 'ricardo.chavez@aurorawater.com',
                'wws_id' => 'WWS010',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'active',
                'service' => 'commercial',
                'address' => '707 Walnut Street, Aurora',
                'contact_number' => '09188990011',
                'approved_at' => now(),
                'approved_by' => 'staff',
            ],
            [
                'name' => 'Camila Ortega',
                'email' => 'camila.ortega@aurorawater.com',
                'wws_id' => 'WWS011',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'active',
                'service' => 'institutional',
                'address' => '808 Spruce Road, Aurora',
                'contact_number' => '09199001122',
                'approved_at' => now(),
                'approved_by' => 'staff',
            ],
            [
                'name' => 'Fernando Silva',
                'email' => 'fernando.silva@aurorawater.com',
                'wws_id' => 'WWS012',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'active',
                'service' => 'residential',
                'address' => '909 Magnolia Lane, Aurora',
                'contact_number' => '09200112233',
                'approved_at' => now(),
                'approved_by' => 'staff',
            ],
            [
                'name' => 'Gabriela Mendoza',
                'email' => 'gabriela.mendoza@aurorawater.com',
                'wws_id' => 'WWS013',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'active',
                'service' => 'commercial',
                'address' => '1010 Rose Avenue, Aurora',
                'contact_number' => '09211223344',
                'approved_at' => now(),
                'approved_by' => 'staff',
            ],
        ];

        // Additional Pending Client Users (20+)
        $pendingClientUsers = [
            [
                'name' => 'Alejandro Ruiz',
                'email' => 'alejandro.ruiz.pending@aurorawater.com',
                'wws_id' => 'WWS014',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'residential',
                'address' => '1111 Tulip Street, Aurora',
                'contact_number' => '09222334455',
            ],
            [
                'name' => 'Lucia Vargas',
                'email' => 'lucia.vargas.pending@aurorawater.com',
                'wws_id' => 'WWS015',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'commercial',
                'address' => '1212 Orchid Road, Aurora',
                'contact_number' => '09233445566',
            ],
            [
                'name' => 'Javier Herrera',
                'email' => 'javier.herrera.pending@aurorawater.com',
                'wws_id' => 'WWS016',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'institutional',
                'address' => '1313 Lily Avenue, Aurora',
                'contact_number' => '09244556677',
            ],
            [
                'name' => 'Daniela Castro',
                'email' => 'daniela.castro.pending@aurorawater.com',
                'wws_id' => 'WWS017',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'residential',
                'address' => '1414 Daisy Lane, Aurora',
                'contact_number' => '09255667788',
            ],
            [
                'name' => 'Roberto Navarro',
                'email' => 'roberto.navarro.pending@aurorawater.com',
                'wws_id' => 'WWS018',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'commercial',
                'address' => '1515 Sunflower Street, Aurora',
                'contact_number' => '09266778899',
            ],
            [
                'name' => 'Elena Rios',
                'email' => 'elena.rios.pending@aurorawater.com',
                'wws_id' => 'WWS019',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'residential',
                'address' => '1616 Jasmine Road, Aurora',
                'contact_number' => '09277889900',
            ],
            [
                'name' => 'Hector Delgado',
                'email' => 'hector.delgado.pending@aurorawater.com',
                'wws_id' => 'WWS020',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'commercial',
                'address' => '1717 Violet Avenue, Aurora',
                'contact_number' => '09288990011',
            ],
            [
                'name' => 'Patricia Vega',
                'email' => 'patricia.vega.pending@aurorawater.com',
                'wws_id' => 'WWS021',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'institutional',
                'address' => '1818 Carnation Lane, Aurora',
                'contact_number' => '09299001122',
            ],
            [
                'name' => 'Oscar Paredes',
                'email' => 'oscar.paredes.pending@aurorawater.com',
                'wws_id' => 'WWS022',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'residential',
                'address' => '1919 Marigold Street, Aurora',
                'contact_number' => '09300112233',
            ],
            [
                'name' => 'Adriana Solis',
                'email' => 'adriana.solis.pending@aurorawater.com',
                'wws_id' => 'WWS023',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'commercial',
                'address' => '2020 Lavender Road, Aurora',
                'contact_number' => '09311223344',
            ],
            [
                'name' => 'Raul Mejia',
                'email' => 'raul.mejia.pending@aurorawater.com',
                'wws_id' => 'WWS024',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'residential',
                'address' => '2121 Iris Avenue, Aurora',
                'contact_number' => '09322334455',
            ],
            [
                'name' => 'Sandra Guzman',
                'email' => 'sandra.guzman.pending@aurorawater.com',
                'wws_id' => 'WWS025',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'commercial',
                'address' => '2222 Poppy Lane, Aurora',
                'contact_number' => '09333445566',
            ],
            [
                'name' => 'Felipe Cordova',
                'email' => 'felipe.cordova.pending@aurorawater.com',
                'wws_id' => 'WWS026',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'institutional',
                'address' => '2323 Azalea Street, Aurora',
                'contact_number' => '09344556677',
            ],
            [
                'name' => 'Veronica Acosta',
                'email' => 'veronica.acosta.pending@aurorawater.com',
                'wws_id' => 'WWS027',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'residential',
                'address' => '2424 Gardenia Road, Aurora',
                'contact_number' => '09355667788',
            ],
            [
                'name' => 'Manuel Ortiz',
                'email' => 'manuel.ortiz.pending@aurorawater.com',
                'wws_id' => 'WWS028',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'commercial',
                'address' => '2525 Hibiscus Street, Aurora',
                'contact_number' => '09366778899',
            ],
            [
                'name' => 'Carmen Flores',
                'email' => 'carmen.flores.pending@aurorawater.com',
                'wws_id' => 'WWS029',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'residential',
                'address' => '2626 Magnolia Avenue, Aurora',
                'contact_number' => '09377889900',
            ],
            [
                'name' => 'Arturo Medina',
                'email' => 'arturo.medina.pending@aurorawater.com',
                'wws_id' => 'WWS030',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'commercial',
                'address' => '2727 Jasmine Lane, Aurora',
                'contact_number' => '09388990011',
            ],
            [
                'name' => 'Lourdes Castillo',
                'email' => 'lourdes.castillo.pending@aurorawater.com',
                'wws_id' => 'WWS031',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'institutional',
                'address' => '2828 Rosewood Road, Aurora',
                'contact_number' => '09399001122',
            ],
            [
                'name' => 'Rogelio Jimenez',
                'email' => 'rogelio.jimenez.pending@aurorawater.com',
                'wws_id' => 'WWS032',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'residential',
                'address' => '2929 Lavender Lane, Aurora',
                'contact_number' => '09400112233',
            ],
            [
                'name' => 'Teresa Romero',
                'email' => 'teresa.romero.pending@aurorawater.com',
                'wws_id' => 'WWS033',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'commercial',
                'address' => '3030 Camellia Street, Aurora',
                'contact_number' => '09411223344',
            ],
            [
                'name' => 'Francisco Mendez',
                'email' => 'francisco.mendez.pending@aurorawater.com',
                'wws_id' => 'WWS034',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'residential',
                'address' => '3131 Peony Avenue, Aurora',
                'contact_number' => '09422334455',
            ],
            [
                'name' => 'Guadalupe Rojas',
                'email' => 'guadalupe.rojas.pending@aurorawater.com',
                'wws_id' => 'WWS035',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'commercial',
                'address' => '3232 Lilac Road, Aurora',
                'contact_number' => '09433445566',
            ],
            [
                'name' => 'Alberto Leon',
                'email' => 'alberto.leon.pending@aurorawater.com',
                'wws_id' => 'WWS036',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'institutional',
                'address' => '3333 Hydrangea Lane, Aurora',
                'contact_number' => '09444556677',
            ],
            [
                'name' => 'Silvia Marquez',
                'email' => 'silvia.marquez.pending@aurorawater.com',
                'wws_id' => 'WWS037',
                'password' => Hash::make('123456'),
                'role' => 'client',
                'status' => 'pending',
                'service' => 'residential',
                'address' => '3434 Zinnia Street, Aurora',
                'contact_number' => '09455667788',
            ],
        ];

        // Create all active staff users
        foreach ($activeStaffUsers as $staffUser) {
            User::create($staffUser);
        }

        // Create all pending staff users
        foreach ($pendingStaffUsers as $staffUser) {
            User::create($staffUser);
        }

        // Create all active client users
        foreach ($activeClientUsers as $clientUser) {
            User::create($clientUser);
        }

        // Create all pending client users
        foreach ($pendingClientUsers as $clientUser) {
            User::create($clientUser);
        }
    }
}